name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Trigger only when backend files change

jobs:
  build-test-coverage:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin 

      - name: Grant Gradle Wrapper Permissions
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Build, Test, and Check Coverage
        run: ./gradlew clean build test jacocoTestReport jacocoTestCoverageVerification
        working-directory: ./backend

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: backend/build/reports/jacoco/test/html/

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: backend/build/libs/*.jar

  # Uncomment and configure when ready for AWS deployment
  # deploy-to-aws:
  #   needs: build-test-coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #     - name: Deploy to AWS
  #       run: echo "Add your deployment commands here"
